sudo: false  #faster
language: ruby
cache: bundler
rvm:
 - 2.4

script: bundle exec jekyll build

# install: gem install jekyll -v 3.8.3 && gem install s3_website
install: bundle install

branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master

after_success: bundle exec s3_website push
